# senkeys values

LOGINPAGE_ENTER_EMAIL = venkatesan.lavanya@gmail.com
LOGINPAGE_ENTER_PASSWORD = Welcome@1
DASHBOARDPAGE_UPLOADJDFILE = C:\\Users\\TTS-USER\\workspace\\com.TrueTech.ScreenIT.NewFlow\\sample\\samplejd\\Java Developer.docx
DASHBOARDPAGE_SELECT_YEARS = 5 years
DASHBOARDPAGE_SELECT_MONTHS = 2 months
DASHBOARDPAGE_SELECT_PRIMARYSKILLS = Core Java
DASHBOARDPAGE_SELECT_SECONDARYSKILLS = Spring Boot
DASHBOARDPAGE_TYPE_JOBDESCRIPTION = i am good in framework construction
DASHBOARDPAGE_TYPE_REMARK = good
SELECTINTERVIEWERPAGE_CHOOSE_SINGLEINTERVIEWER = 0
SELECTINTERVIEWERPAGE_CHOOSE_ANOTHERINTERVIEW = 0
CANDIDATEPROFILEPAGE_UPLOADCANDIDATERESUME = C:\\Users\\TTS-USER\\workspace\\com.TrueTech.ScreenITFlow.DDD\\sample\\samplejd\\Sathish.docx
CANDIDATEPROFILEPAGE_UPLOADMULTIPLECANDIDATERESUME = C:\\Users\\TTS-USER\\workspace\\com.TrueTech.ScreenIT.NewFlow\\sample\\samplejd\\Sathish.docx \n C:\\Users\\TTS-USER\\workspace\\com.TrueTech.ScreenIT.NewFlow\\sample\\samplejd\\Automation Testing.docx \n C:\\Users\\TTS-USER\\workspace\\com.TrueTech.ScreenIT.NewFlow\\sample\\samplejd\\Java Developer.docx \n C:\\Users\\TTS-USER\\workspace\\com.TrueTech.ScreenIT.NewFlow\\sample\\samplejd\\Mrinalini V.docx
CANDIDATEPROFILEPAGE_SELECTDATE = 18
CANDIDATEPROFILEPAGE_SELECTTIME = 10
CANDIDATEPROFILEPAGE_SELECTSEC = 30
CANDIDATEPROFILEPAGE_SELECTSUFFIX = am
CANDIDATEPROFILEPAGE_ANOTHER_SELECTDATE = 14
CANDIDATEPROFILEPAGE_ANOTHER_SELECTTIME = 5
CANDIDATEPROFILEPAGE_ANOTHER_SELECTSEC = 30
CANDIDATEPROFILEPAGE_ANOTHER_SELECTSUFFIX = pm
CANDIDATEPROFILEPAGE_EDITINFO = sathish
CANDIDATEPROFILEPAGE_EDITENDINFO = S
RESCHEDULEPAGE_SELECTREASON = Candidate is not available
RESCHEDULEPAGE_COMMENT = im not available
EMAILPAGE_TYPE_EMAIL = schedules@truetechsolutions.in
EMAILPAGE_TYPE_PASSWORD = KYOSxB2hHsPhpjX
EMAILPAGE_CLICK_ACCEPTORDECLINE = Accept
EMAILPAGE_TYPE_NAME = sathish
CANDIDATERESUME_INDEX = 0


 
 