# senkeys values

LOGINPAGE_ENTER_EMAIL = venkatesan.lavanya@gmail.com
LOGINPAGE_ENTER_PASSWORD = Welcome@1
DASHBOARDPAGE_UPLOADJDFILE = C:\\Users\\TTS-USER\\workspace\\com.TrueTech.ScreenITFlow.DDD\\sample\\samplejd\\Java Developer.docx
DASHBOARDPAGE_SELECT_YEARS = 9 years
DASHBOARDPAGE_SELECT_MONTHS = 7 months
DASHBOARDPAGE_SELECT_PRIMARYSKILLS = Core Java
DASHBOARDPAGE_SELECT_SECONDARYSKILLS = Agile methodology
DASHBOARDPAGE_TYPE_JOBDESCRIPTION = i am good in framework construction
DASHBOARDPAGE_TYPE_REMARK = good
SELECTINTERVIEWERPAGE_CHOOSE_SINGLEINTERVIEWER = 6
SELECTINTERVIEWERPAGE_CHOOSE_ANOTHERINTERVIEW = 8
CANDIDATEPROFILEPAGE_UPLOADCANDIDATERESUME = C:\\Users\\TTS-USER\\workspace\\com.TrueTech.ScreenITFlow.DDD\\sample\\samplejd\\Sathish.docx
CANDIDATEPROFILEPAGE_SELECTDATE = 28
CANDIDATEPROFILEPAGE_SELECTTIME = 3
CANDIDATEPROFILEPAGE_SELECTSEC = 30
CANDIDATEPROFILEPAGE_SELECTSUFFIX = pm
CANDIDATEPROFILEPAGE_ANOTHER_SELECTDATE = 27
CANDIDATEPROFILEPAGE_ANOTHER_SELECTTIME = 10
CANDIDATEPROFILEPAGE_ANOTHER_SELECTSEC = 30
CANDIDATEPROFILEPAGE_ANOTHER_SELECTSUFFIX = am
CANDIDATEPROFILEPAGE_EDITINFO = sathish
CANDIDATEPROFILEPAGE_EDITENDINFO = S
RESCHEDULEPAGE_SELECTREASON = Candidate is not available
RESCHEDULEPAGE_COMMENT = im not available
EMAILPAGE_TYPE_EMAIL = poc@shivaami.today
EMAILPAGE_TYPE_PASSWORD = Dummy123#
EMAILPAGE_CLICK_ACCEPTORDECLINE = Accept
EMAILPAGE_TYPE_NAME = sathish


 
 